server {
    listen 80;
    server_name _;

    # Default root (not strictly needed since we use alias below)
    root /usr/share/nginx/html;

    # Serve the app under /dynsvg
    location /data/ {
        alias /opt/data/;
        types {
            application/yaml yaml yml;
        }
        default_type application/yaml;

        expires off;

        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
        add_header Pragma "no-cache" always;
        add_header Surrogate-Control "no-store" always;

        add_header X-Content-Type-Options "nosniff" always;

        autoindex off;
    }

    location /wasm/ {
        alias /opt/wasm/;
    }
}
