[package]
name = "bimpl"
version = "0.1.0"
edition = "2021"
description = "Library crate that contains the possible layouts"


[dependencies]
builder_m4cro = "0.2.0"
rusttype = "0.9.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
